all:

open1:open1.c
	gcc open1.c -o open1
open2:open2.c
	gcc open2.c -o open2
write:write.c
	gcc write.c -o write
write1:write1.c
	gcc write1.c -o write1
write2:write2.c
	gcc write2.c -o write2
read:	read.c
	gcc read.c -o read
read1:	read1.c
	gcc read1.c -o read1

clean :
	rm -rf open1 open2 write1 write2 write read read1


